#aws cloudformation create-stack --stack-name cx-lambda --template-body file://lambda.yml --capabilities CAPABILITY_IAM
---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda to trigger Checkmarx Scan'
Parameters:
  CxUrl:
    Description: 'Checkmarx URL'
    Type: String
    Default: https://cx.xxxx.com
  CxUser:
    Description: 'Checkmarx Service Account User'
    Type: String
    NoEcho: True
  CxPassword:
    Description: 'Checkmarx Service Account Password'
    Type: String
    NoEcho: True
  CxTeam:
    Description: 'Checkmarx base team'
    Type: String
    Default: \CxServer\SP\Checkmarx\Automation
  CxPreset:
    Description: 'Scan Preset'
    Type: String
    Default: Checkmarx Default
Resources:
  CxScanLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cx-aws-test
        S3Key: machina-lambda/cx-lambda-1.0.zip
      FunctionName: cxScan
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      Timeout: 20
      MemorySize: 128
      Role:
        !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          CX_USER: !Ref CxUser
          CX_PASSWORD: !Ref CxPassword
          CX_URL: !Ref CxUrl
          CX_TEAM: !Ref CxTeam
          CX_PRESET: !Ref CxPreset

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'lambda.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      Path: "/"
      ManagedPolicyArns: ["arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"]
      Policies:
      - PolicyName: CodePipeline-lambda
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - codepipeline:PutJobSuccessResult
            - codepipeline:PutJobFailureResult
            Resource: "*"
            Effect: Allow
Outputs:
  LambdaFunction:
    Description: Lambda export values
    Value:
      !GetAtt CxScanLambdaFunction.Arn
    Export:
      Name: CxScan
      Arn:
        !GetAtt CxScanLambdaFunction.Arn
